version: "3"

services:
  app:
    container_name: BirdsCreekBackend
    image: webdeveloperandrew/bcfarmsupplybackend
    restart: always
    ports:
      - "4000:4000"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .images:/images
      - .settings:/settings

  mongo:
    container_name: BirdsCreekMongoDB
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - bc_mongodb:/data/db
      - bc_mongodb_config:/data/configdb
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels: 
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: jwilder/nginx-proxy
  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl-nginx
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
  website:
    image: webdeveloperandrew/bcfarmsupplywebsite    
    container_name: website
    ports: 
      - "8080:8080"
    environment:
      - WEBSITE=birdscreekfarmsupply.ca
      - PORT=8080      
      - VIRTUAL_HOST=birdscreekfarmsupply.ca,www.birdscreekfarmsupply.ca,birdscreekfarmsupply.com,www.birdscreekfarmsupply.com
      - LETSENCRYPT_HOST=birdscreekfarmsupply.ca,www.birdscreekfarmsupply.ca,birdscreekfarmsupply.com,www.birdscreekfarmsupply.com
      - LETSENCRYPT_EMAIL=webdeveloperandrew@gmail.com
  nodemailer:
    image: webdeveloperandrew/nodemailer
    container_name: nodemailer
    ports:
      - "3000:3000"
    environment:
      - GMAILLOGIN=emailservice2018on@gmail.com
      - CLIENTID=396375115656-3mrdnqru0bo2nf5qnr205nm7n51tb7tr.apps.googleusercontent.com
      - CLIENTSECRET=nSf7QoGOvm9k7ApQDEqe69wv
      - REFRESHTOKEN=1/_85Xs8M28BTiv93li0iBwUkWGfseO4Lj3ilJe67SdKA
      - EMAIL=bcfeed@nexicom.net

volumes:
  certs:
  vhost:
  html:
  bc_mongodb:
  bc_mongodb_config:
  images:
  settings: